image: Visual Studio 2019
init:
  - git config --global core.autocrlf true
environment:
  nodejs_version: "12"
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - ps: Install-Product node $env:nodejs_version
  - cmd: choco install dotnetcore-sdk --pre
  - dotnet --version
  - cd src
  - dotnet restore
build_script:
- dotnet build
before_build:
- appveyor-retry dotnet restore -v Minimal
test_script:
- cd CertificateManagerTests
- dotnet test
